<a href="https://colab.research.google.com/github/RomanKunal/Machine-Learning/blob/main/LR2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Own linear regression logic


In [ ]:
class LR:
  def __init__(self):
    self.m=None
    self.m=None
  def fit(self,X_train,Y_train):
    num=0
    den=0
    for i in range(X_train.shape[0]):
      num=num+((X_train[i]-X_train.mean())*(Y_train[i]-Y_train.mean()))
      den=den+((X_train[i]-X_train.mean())**2)
    self.m=num/den
    self.b=Y_train.mean()-self.m*X_train.mean()
  def predict(self,X_test):
    return self.m*X_test+self.b

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [ ]:
data=pd.read_csv("/content/placement.csv")
data.head()

cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [ ]:
X=data.iloc[:,0:1]
Y=data.iloc[:,-1]

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

In [8]:
X_train.values

array([[7.14],
       [8.93],
       [5.42],
       [5.1 ],
       [7.77],
       [6.76],
       [6.89],
       [6.68],
       [7.91],
       [7.89],
       [8.71],
       [7.95],
       [6.61],
       [6.26],
       [6.53],
       [6.42],
       [5.11],
       [6.09],
       [6.93],
       [7.04],
       [5.94],
       [6.05],
       [5.83],
       [5.95],
       [9.31],
       [5.58],
       [7.88],
       [6.13],
       [7.76],
       [4.85],
       [6.19],
       [8.6 ],
       [6.07],
       [7.18],
       [5.12],
       [7.39],
       [8.25],
       [8.28],
       [7.13],
       [7.35],
       [5.66],
       [5.99],
       [8.01],
       [7.14],
       [6.34],
       [6.89],
       [5.42],
       [6.47],
       [7.69],
       [7.4 ],
       [7.28],
       [5.95],
       [7.38],
       [6.93],
       [8.99],
       [7.36],
       [7.08],
       [5.38],
       [7.56],
       [8.22],
       [5.84],
       [6.78],
       [7.19],
       [7.28],
       [6.79],
       [6.12],
       [6.

In [9]:
lr=LR()
lr.fit(X_train.values,Y_train.values)


In [10]:
lr.m

array([0.55795197])

In [11]:
lr.b

array([-0.89611192])

In [15]:
lr.predict(8.9)

array([4.06966064])